---

sudo: false

dist: trusty

cache:
  directories:
    - vendor/bundle

language: ruby

addons:
  apt:
    packages:
      - indent
      - shellcheck

matrix:
  include:
    - rvm: 2.2.7
      env: LIBEDIT=true
      addons:
        apt:
          packages:
            - libedit-dev

    - rvm: 2.2.7-clang
      env: LIBEDIT=true

    - rvm: 2.3.4
      env: LIBEDIT=true

    - rvm: 2.3.4-clang
      env: LIBEDIT=true

    - rvm: 2.4.1
      env: LIBEDIT=true

    - rvm: 2.4.1-clang
      env: LIBEDIT=true

    - rvm: 2.2.7
      env: LIBEDIT=false

    - rvm: 2.2.7-clang
      env: LIBEDIT=false

    - rvm: 2.3.4
      env: LIBEDIT=false

    - rvm: 2.3.4-clang
      env: LIBEDIT=false

    - rvm: 2.4.1
      env: LIBEDIT=false

    - rvm: 2.4.1-clang
      env: LIBEDIT=false

  allow_failures:
    - rvm: ruby-head
      env: LIBEDIT=true

    - rvm: ruby-head-clang
      env: LIBEDIT=true

    - rvm: ruby-head
      env: LIBEDIT=false

    - rvm: ruby-head-clang
      env: LIBEDIT=false

env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

branches:
  only:
    - master
    - chore/update_codeclimate_test_reporter

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - if [ "$LIBEDIT" == "true" ]; then
      rvm reinstall "$TRAVIS_RUBY_VERSION" --configure --enable-libedit
                                           --rubygems ignore;
    fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - ./cc-test-reporter before-build
  - script/ci.sh
  - ./cc-test-reporter format-coverage --output coverage/codeclimate.$TRAVIS_RUBY_VERSION.json

jobs:
  include:
    - stage: coverage
      script: ./cc-test-reporter sum-coverage coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage
