---

sudo: required

dist: trusty

cache:
  directories:
    - vendor/bundle

language: ruby

rvm:
  - 2.2.7
  - 2.2.7-clang
  - 2.3.4
  - 2.3.4-clang
  - 2.4.1
  - 2.4.1-clang
  - ruby-head
  - ruby-head-clang

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang

env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

  matrix:
    - "LIBEDIT=true"
    - "LIBEDIT=false"

branches:
  only:
    - master
    - chore/update_codeclimate_test_reporter

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get install indent shellcheck
  - if [ "$LIBEDIT" == "true" ]; then
      sudo apt-get install libedit-dev;
    fi

install:
  - if [ "$LIBEDIT" == "true" ]; then
      rvm reinstall "$TRAVIS_RUBY_VERSION" --configure --enable-libedit
                                           --rubygems ignore;
    fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - ./cc-test-reporter before-build
  - script/ci.sh
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
