---

init:
  - set PATH=C:\ruby%ruby_version%\bin;C:\Program Files\Git\cmd;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Windows\system32;C:\Windows
  - echo %PATH%

  - if %ruby_version% == _trunk (
      appveyor DownloadFile https://dl.bintray.com/msp-greg/ruby_windows/ruby_trunk.7z -FileName C:/ruby_trunk.7z &
      7z x C:/ruby_trunk.7z -oC:/ruby_trunk &
      C:/ruby_trunk/trunk_install.cmd
    )

version: "{build}"

install:
  - ruby --version
  - where ruby

  - gem update --system --no-document
  - gem --version
  - where gem

  - gem install bundler --no-document
  - bundler --version
  - where bundler

  - bundle config force_ruby_platform true
  - bundle install --jobs 3 --retry 3

build_script:
  - bundle exec rake clobber
  - bundle exec rake compile

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: '22'
    - ruby_version: 22-x64
    - ruby_version: '23'
    - ruby_version: 23-x64
    - ruby_version: '24'
    - ruby_version: 24-x64
    - ruby_version: _trunk

  codeclimate_repo_token: '02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408'

matrix:
  fast_finish: true

  allow_failures:
    - ruby_version: _trunk

branches:
  only:
    - master

notifications:
  - provider: Email

    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
